#!/bin/bash

echo
echo "System Summary"
#echo "----------------------------------------"
sqlite3 -header -column tails.sqlite <<!
.width 15 6;
select version as schema,count(*) as count from systems group by 1 order by 1  ;
!

echo
echo "Bearer Summary"
#echo "----------------------------------------"
sqlite3 -header -column tails.sqlite <<!
.width 15 6;
select bearer,count(*) as count from bearers where enabled  group by 1 order by 1  ;
!

echo
echo "FBO Summary"
#echo "----------------------------------------"
sqlite3 -header -column tails.sqlite <<!
.width 6 6;
select case fbo when 0 then 'off' else 'on' end as FBO,count(*) as count from radios where device='wlan1'  group by 1 order by 1  ;
!

echo
echo "SSID Summary"
#echo "----------------------------------------"
sqlite3 -header -column tails.sqlite <<!
.width 6 23 6;
select device,ssid,count(*) as count from aps  group by 2,1 order by 2,1  ;
!

echo
echo "WPA Summary"
#echo "----------------------------------------"
sqlite3 -header -column tails.sqlite <<!
.width 6 6 6;
select device,case psk when '' then '' else 'PWD' end  as PSK ,count(*) as cnt from aps  group by 1,2;
!

echo
echo "RC Airshow Summary"
#echo "----------------------------------------"
sqlite3 -header -column tails.sqlite <<!
.width 15 6;
select nonkey,count(*) as count from rcairshows where nonkey not in ('fmstype') group by 1;
!


echo
echo "WOW Summary"
#echo "----------------------------------------"
sqlite3 -header -column tails.sqlite <<!
.width 15 6;
select wow,count(*) as cnt from systems  group by 1;
!


echo
echo "WOW Discrete Summary"
#echo "----------------------------------------"
sqlite3 -header -column tails.sqlite <<!
.width 15 6;
select gpio,count(*) as count from functions where id=="WOW" group by 1;
!


echo
echo "Low speed busses"
#echo "----------------------------------------"
sqlite3 -header -column tails.sqlite <<!
.width 15 6;
select id, count(*) as count from a429s  
where speed=='low'
group by 1 order by 1;
!

echo
echo "Low speed bus count"
#echo "----------------------------------------"
sqlite3 -header -column tails.sqlite <<!
.width 15 6;
select count as "Nr of Busses", count(*) as number from (
	select serial, count(*) as count from a429s  
	where speed=='low'
	group by 1 
)  as ccnt
group by 1 order by 1;
!

echo
echo "Port Usage Summary"
#echo "----------------------------------------"
sqlite3 -header -column tails.sqlite <<!
.width 12 12 12 6;
select equip,name,vid,count(*) as count from ports group by 1,2,3 order by 1,2,3;
!


echo
echo "AP Band Summary"
#echo "----------------------------------------"
sqlite3 -header -column tails.sqlite <<!
.width 12 12 6;
select device,band,count(*) as count from radios group by 1,2;
!


exit

echo
echo "Low speed labels"
#echo "----------------------------------------"
sqlite3 -header -column tails.sqlite <<!
.width 30 6;
select l.name, count(*) as count from labels l 
join a429s a 
on l.serial=a.serial and ('rx' ||l.port) == a.id 
where a.speed=='low'
group by 1;
!



